### ISSUE TITLE
Implement SQLite

### ISSUE THREAD

**Issue by Waterblokey** [cse110-sp24-group34/cse110-sp24-group34#2]
Use SQLite to store posts

**Comment by MauricioESerrano** [comment]
Jason and Mauricio implemented SQLite

**Comment by MauricioESerrano** [comment]
Created 3 more helper functions, fixed unforeseen issues in pre-existing functions, cleaned up code and added comments to function functionality.

**Comment by MauricioESerrano** [comment]
fixed any remaining issues that Sumukh had and all in all SQLite is fully implemented. 

Any bugs and issues can be addressed via "bug" issue tags.
