### ISSUE TITLE
CSS bugs

### ISSUE THREAD

**Issue by Augustus31** [cse110-sp24-group34/cse110-sp24-group34#32]
Current bugs with css:
- elements on top bar are too big
- top bar spills over onto rest of page if enough tags are made
- there should probably be a max size for any particular tag button, otherwise it can take up the entire top bar

**Comment by jtung0705** [comment]
Is top bar elements too big a legit concern or is is style wise, do you mean it spills over? Mind taking a ss to show

**Comment by jtung0705** [comment]
split into three different issues instead
