### ISSUE TITLE
Tag Selector: add visuals to show that a tag is selected

### ISSUE THREAD

**Issue by Nickpizzablock** [cse110-sp24-group34/cse110-sp24-group34#37]
Issue Description:
When you click on a tag in the dropdown tag selector at the top of the website, the tag does not have an indicator that signifies the tag has been selected.

Potential Solutions:
- Change the background of the tag when the button is clicked.

**Comment by Nickpizzablock** [comment]
Also, change the color to something darker when the tag is selected, since grey looks like it is unselected

**Comment by jtung0705** [comment]
attached to branch
